version: '1.0'

services:
  db:
    container_name: postgres-container
    image: "postgres:15"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=db
    ports:
      - "5432:5432" 

volumes:
  data: {}